name: quidpay
description: Quidpay
version: 0.1.0
author: Jeremiah Ogbomo <jeremiahogbomo@gmail.com>
homepage: https://github.com/jogboms/quidpay.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  crypto: ^2.0.6
  tripledes: ^2.1.0
  http: ^0.12.0
  built_value: ^6.4.0
  built_collection: ^4.2.0
  meta: ^1.1.7
  convert: ^2.1.1

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.4.0
  test_coverage: ^0.2.0
  build_runner: ^1.3.1
  built_value_generator: ^6.4.0